//LLVM

#ifdef WIN32

#ifdef _DEBUG

#pragma comment(lib, "../llvm/bin/lib/Debug/clangDriver.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangBasic.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangFrontend.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangAnalysis.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangRewrite.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangSema.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangAST.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangParse.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/clangLex.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMSystem.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMSupport.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMBitReader.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCore.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMBitWriter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMSelectionDAG.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMTransformUtils.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMInstrumentation.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMScalarOpts.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMipo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMHello.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMLinker.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMAnalysis.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMipa.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMC.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMARMCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMARMInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMARMAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCBackend.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCBackendInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCppBackend.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMCppBackendInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMipsCodeGen")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMipsInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMipsAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMSIL.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMMSILInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMPowerPCCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMPowerPCInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMPowerPCAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMX86CodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMX86Info.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMX86AsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMX86AsmParser.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMExecutionEngine.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMInterpreter.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMJIT.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMTarget.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMAsmParser.lib")
#pragma comment(lib, "../llvm/bin/lib/Debug/LLVMDebugger.lib")

#else

#pragma comment(lib, "../llvm/bin/lib/Release/clangDriver.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangBasic.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangFrontend.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangAnalysis.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangRewrite.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangSema.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangAST.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangParse.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/clangLex.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMSystem.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMSupport.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMBitReader.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCore.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMBitWriter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMSelectionDAG.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMTransformUtils.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMInstrumentation.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMScalarOpts.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMipo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMHello.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMLinker.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMAnalysis.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMipa.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMC.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMARMCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMARMInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMARMAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCBackend.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCBackendInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCppBackend.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMCppBackendInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMipsCodeGen")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMipsInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMipsAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMSIL.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMMSILInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMPowerPCCodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMPowerPCInfo.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMPowerPCAsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMX86CodeGen.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMX86Info.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMX86AsmPrinter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMX86AsmParser.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMExecutionEngine.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMInterpreter.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMJIT.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMTarget.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMAsmParser.lib")
#pragma comment(lib, "../llvm/bin/lib/Release/LLVMDebugger.lib")

#endif

#endif