/////////////////////////////////////////////////////////////////////////////
// Name:        DlgEventKeyDown.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     04/27/06 14:20:22
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 04/27/06 14:20:22

#ifndef _DLGEVENTKEYDOWN_H_
#define _DLGEVENTKEYDOWN_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "DlgEventKeyDown.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/listctrl.h"
#include "wx/statline.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10011
#define SYMBOL_DLGEVENTKEYDOWN_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_DLGEVENTKEYDOWN_TITLE _("Key Down")
#define SYMBOL_DLGEVENTKEYDOWN_IDNAME ID_DIALOG
#define SYMBOL_DLGEVENTKEYDOWN_SIZE wxSize(400, 300)
#define SYMBOL_DLGEVENTKEYDOWN_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * DlgEventKeyDown class declaration
 */

class DlgEventKeyDown: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( DlgEventKeyDown )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DlgEventKeyDown( );
    DlgEventKeyDown( wxWindow* parent, wxWindowID id = SYMBOL_DLGEVENTKEYDOWN_IDNAME, const wxString& caption = SYMBOL_DLGEVENTKEYDOWN_TITLE, const wxPoint& pos = SYMBOL_DLGEVENTKEYDOWN_POSITION, const wxSize& size = SYMBOL_DLGEVENTKEYDOWN_SIZE, long style = SYMBOL_DLGEVENTKEYDOWN_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DLGEVENTKEYDOWN_IDNAME, const wxString& caption = SYMBOL_DLGEVENTKEYDOWN_TITLE, const wxPoint& pos = SYMBOL_DLGEVENTKEYDOWN_POSITION, const wxSize& size = SYMBOL_DLGEVENTKEYDOWN_SIZE, long style = SYMBOL_DLGEVENTKEYDOWN_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin DlgEventKeyDown event handler declarations

////@end DlgEventKeyDown event handler declarations

////@begin DlgEventKeyDown member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DlgEventKeyDown member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin DlgEventKeyDown member variables
////@end DlgEventKeyDown member variables
};

#endif
    // _DLGEVENTKEYDOWN_H_
