/////////////////////////////////////////////////////////////////////////////
// Name:        DlgEventKeyDown.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     04/27/06 14:20:22
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 04/27/06 14:20:22

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "DlgEventKeyDown.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "DlgEventKeyDown.h"

////@begin XPM images
////@end XPM images

/*!
 * DlgEventKeyDown type definition
 */

IMPLEMENT_DYNAMIC_CLASS( DlgEventKeyDown, wxDialog )

/*!
 * DlgEventKeyDown event table definition
 */

BEGIN_EVENT_TABLE( DlgEventKeyDown, wxDialog )

////@begin DlgEventKeyDown event table entries
////@end DlgEventKeyDown event table entries

END_EVENT_TABLE()

/*!
 * DlgEventKeyDown constructors
 */

DlgEventKeyDown::DlgEventKeyDown( )
{
}

DlgEventKeyDown::DlgEventKeyDown( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create(parent, id, caption, pos, size, style);
}

/*!
 * DlgEventKeyDown creator
 */

bool DlgEventKeyDown::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin DlgEventKeyDown member initialisation
////@end DlgEventKeyDown member initialisation

////@begin DlgEventKeyDown creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    SetParent(parent);
    CreateControls();
    GetSizer()->Fit(this);
    GetSizer()->SetSizeHints(this);
    Centre();
////@end DlgEventKeyDown creation
    return true;
}

/*!
 * Control creation for DlgEventKeyDown
 */

void DlgEventKeyDown::CreateControls()
{    
////@begin DlgEventKeyDown content construction
    // Generated by DialogBlocks, 04/27/06 15:32:20 (unregistered)

    wxXmlResource::Get()->LoadDialog(this, GetParent(), _T("ID_DIALOG"));
////@end DlgEventKeyDown content construction

    // Create custom windows not generated automatically here.

////@begin DlgEventKeyDown content initialisation

////@end DlgEventKeyDown content initialisation
}

/*!
 * Should we show tooltips?
 */

bool DlgEventKeyDown::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap DlgEventKeyDown::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin DlgEventKeyDown bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end DlgEventKeyDown bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon DlgEventKeyDown::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin DlgEventKeyDown icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end DlgEventKeyDown icon retrieval
}
