/////////////////////////////////////////////////////////////////////////////
// Name:        MainFrame.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     01/08/06 14:25:46
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 01/08/06 14:25:46

#ifndef _MAINFRAME_H_
#define _MAINFRAME_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "MainFrame.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/frame.h"
#include "wx/toolbar.h"
////@end includes

#include <wx/ifm/ifm.h>
#include "wxGed/wxGedStatusBar.h"
#include "wxGed/wxGedControls.h"
#include "wx/toolbar.h"
#include "wx/docview.h"



/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRAME 10000
#define SYMBOL_WXMAINFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxCLOSE_BOX
#define SYMBOL_WXMAINFRAME_TITLE _("Game Editor")
#define SYMBOL_WXMAINFRAME_IDNAME ID_FRAME
#define SYMBOL_WXMAINFRAME_SIZE wxSize(800, 600)
#define SYMBOL_WXMAINFRAME_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

WX_DECLARE_HASH_MAP(int, wxWindow*, wxIntegerHash, wxIntegerEqual, wxWindowMap);
WX_DECLARE_HASH_MAP(int, wxString, wxIntegerHash, wxIntegerEqual, wxIntStringMap);

/*!
 * wxMainFrame class declaration
 */

class SDLPanel;
class PanelProperty;
class wxJigsawEditorMainFrame;
class PanelActors;
class PanelScript;

class wxMainFrame: public wxFrame
{    
    DECLARE_CLASS( wxMainFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxMainFrame( );
    wxMainFrame( wxString _applicationDir, wxWindowID id = SYMBOL_WXMAINFRAME_IDNAME, const wxString& caption = SYMBOL_WXMAINFRAME_TITLE, const wxPoint& pos = SYMBOL_WXMAINFRAME_POSITION, const wxSize& size = SYMBOL_WXMAINFRAME_SIZE, long style = SYMBOL_WXMAINFRAME_STYLE );

	~wxMainFrame( );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXMAINFRAME_IDNAME, const wxString& caption = SYMBOL_WXMAINFRAME_TITLE, const wxPoint& pos = SYMBOL_WXMAINFRAME_POSITION, const wxSize& size = SYMBOL_WXMAINFRAME_SIZE, long style = SYMBOL_WXMAINFRAME_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

	

////@begin wxMainFrame event handler declarations

    /// wxEVT_CLOSE_WINDOW event handler for ID_FRAME
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_ERASE_BACKGROUND event handler for ID_FRAME
    void OnEraseBackground( wxEraseEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_NEW
    void OnMenuNewClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_OPEN
    void OnMenuOpenClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_EXIT
    void OnMenuExitClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_TITLE_BAR
    void OnMenuTitleBarClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_LAYOUT_RESET
    void OnMenuLayoutResetClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_GAME_MODE
    void OnGameModeClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_MRU
    void OnMRUFile( wxCommandEvent& event );

////@end wxMainFrame event handler declarations

	void OnMove(wxMoveEvent & event);
	void OnSize(wxSizeEvent & event);
	void OnIconize(wxIconizeEvent & event);
	void OnMaximize(wxMaximizeEvent & event);

////@begin wxMainFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxMainFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxMainFrame member variables
////@end wxMainFrame member variables


	void OnActivate(wxActivateEvent& event);

	void OnMenuOpen(wxMenuEvent &event);
	void OnMenuPanel(wxCommandEvent &event);
	void OnMenuLoadLayout(wxCommandEvent &event);

    void OnMenuLayoutSaveClick( wxCommandEvent& event );
    void OnMenuLayoutSaveAsClick( wxCommandEvent& event );
    void OnMenuLayoutDeleteClick( wxCommandEvent& event );
    void OnMenuLayoutRestoreClick( wxCommandEvent& event );
	void OnLayoutState(wxLayoutStateEvent& event);

	void OnDropFiles(wxDropFilesEvent & event);



	static wxMainFrame *Get() {return mainFrame;}
	wxIFMLayoutControl *GetLayoutControl() {return layoutControl;}
	wxPanel *GetRootPanel() {return m_root_panel;}
	
	void AddLayout(wxString name);
	void RemoveLayout(wxString name);

	bool Show(bool show = true);
	void HidePanels();
	void SetupSDLPanelGameModePosition();

	const wxString& getApplicationDir() {return applicationDir;}


private:
    void Setup_wxIFM();
	void AppendPanelToMenu(wxWindow *window, wxString &name);
	void AppendLayoutToMenu(wxString name);
	void RemoveLayoutFromMenu(wxString name);
	void SetupMRU();


    
    wxInterfaceManager *m_ifm;
    wxPanel *m_root_panel;
	wxWindowMap m_panels;
	wxIntStringMap m_layouts;

	wxGedStatusBar* statusBar;

	wxIFMLayoutControl *layoutControl;

	wxString applicationDir;
	wxFileHistory mru;

	bool bMaximized;

	static wxMainFrame *mainFrame;

	SDLPanel *sdlPanel;
	PanelProperty *panelProperty;
	wxJigsawEditorMainFrame *pBehavior;
	PanelActors *panelActors;
	PanelScript *panelScript;
};

#endif
    // _MAINFRAME_H_
