#ifndef KYRA_font_INCLUDED
#define KYRA_font_INCLUDED

// Machine generated Kyra header file.
// Will be overwritten by the encoder.
// Generated by kyra version 2.0.4

// Section 0: 
const U32              CONSOLE = (1 << 0);		// 1
const U32                 NONE = (2 << 0);		// 2
const U32                ARIAL = (3 << 0);		// 3

#endif
