#ifndef KYRA_space_INCLUDED
#define KYRA_space_INCLUDED

// Machine generated Kyra header file.
// Will be overwritten by the encoder.
// Generated by kyra version 2.0.4

// Section 0: 
const U32          SPACE_STARS = (1 << 0);		// 1
const U32           SPACE_NONE = (2 << 0);		// 2
const U32          SPACE_SMALL = (3 << 0);		// 3
const U32       SPACE_INSIGNIA = (4 << 0);		// 4
const U32            SPACE_MED = (5 << 0);		// 5
const U32           SPACE_BODY = (6 << 0);		// 6
const U32           SPACE_TAIL = (7 << 0);		// 7
const U32          SPACE_LARGE = (8 << 0);		// 8
const U32         SPACE_ENGINE = (9 << 0);		// 9
const U32            SPACE_CAR = (10 << 0);		// 10
const U32        SPACE_CABOOSE = (11 << 0);		// 11
const U32          SPACE_TRAIN = (12 << 0);		// 12
const U32         SPACE_OBLONG = (13 << 0);		// 13
const U32         SPACE_SPHERE = (14 << 0);		// 14
const U32         SPACE_BULLET = (15 << 0);		// 15

#endif
