#ifndef KYRA_standardtest_INCLUDED
#define KYRA_standardtest_INCLUDED

// Machine generated Kyra header file.
// Will be overwritten by the encoder.
// Generated by kyra version 2.0.4

// Section 0: 
const U32              NOALPHA = (1 << 0);		// 1
const U32                ALPHA = (2 << 0);		// 2
const U32                 NONE = (3 << 0);		// 3
const U32           BACKGROUND = (4 << 0);		// 4

#endif
