all:	libgvplugin_dot_layout.a libgvplugin_neato_layout.a libgvplugin_usershape_gd.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
	    -I$(ROOT) \
        -I../common \
        -I../gvc \
        -I../pathplan \
        -I../graph \
        -I../cdt \
        -I../gd \
        $(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H

OBJS_DL = gvplugin_dot_layout.o gvlayout_dot_layout.o 
OBJS_NL = gvplugin_neato_layout.o gvlayout_neato_layout.o
OBJS_US = gvplugin_usershape_gd.o gvusershape_gd.o

libgvplugin_dot_layout.a : $(OBJS_DL)
	$(RM) libgvplugin_dot_layout.a
	$(AR) cr libgvplugin_dot_layout.a $(OBJS_DL)
	$(RANLIB) libgvplugin_dot_layout.a

libgvplugin_neato_layout.a : $(OBJS_NL)
	$(RM) libgvplugin_neato_layout.a
	$(AR) cr libgvplugin_neato_layout.a $(OBJS_NL)
	$(RANLIB) libgvplugin_neato_layout.a

libgvplugin_usershape_gd.a : $(OBJS_US)
	$(RM) libgvplugin_usershape_gd.a
	$(AR) cr libgvplugin_usershape_gd.a $(OBJS_US)
	$(RANLIB) libgvplugin_usershape_gd.a

install: libgvplugin_dot_layout.a libgvplugin_neato_layout.a libgvplugin_usershape_gd.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvplugin_dot_layout.a $(LIBDIR)
	$(INSTALL) libgvplugin_neato_layout.a $(LIBDIR)
	$(INSTALL) libgvplugin_usershape_gd.a $(LIBDIR)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a ptest
