#ifndef KYRA_tutorial1_INCLUDED
#define KYRA_tutorial1_INCLUDED

// Machine generated Kyra header file.
// Will be overwritten by the encoder.
// Generated by kyra version 1.6.3

// Section 0: 
const U32        TUT1_PARTICLE = (1 << 0);		// 1
const U32            TUT1_MAGE = (2 << 0);		// 2
const U32            TUT1_NONE = (3 << 0);		// 3
const U32          TUT1_CARPET = (4 << 0);		// 4

#endif
