<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: SDL - Win32 (WCE x86) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "c:\temp\RSP545.tmp" with contents
[
commctrl.lib coredll.lib corelibc.lib /nologo /base:"0x00100000" /stack:0x10000,0x1000 /entry:"_DllMainCRTStartup" /dll /incremental:yes /pdb:"../../../../output/SDL.pdb" /debug /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"../../../../output/SDL.dll" /implib:"../../../../output/SDL.lib" /subsystem:windowsce,3.00 /MACHINE:IX86 
\GAMEDEVELOPMENT\output\SDL\SDL.obj
\GAMEDEVELOPMENT\output\SDL\SDL_active.obj
\GAMEDEVELOPMENT\output\SDL\SDL_audio.obj
\GAMEDEVELOPMENT\output\SDL\SDL_audiocvt.obj
\GAMEDEVELOPMENT\output\SDL\SDL_audiodev.obj
\GAMEDEVELOPMENT\output\SDL\SDL_audiomem.obj
\GAMEDEVELOPMENT\output\SDL\SDL_blit.obj
\GAMEDEVELOPMENT\output\SDL\SDL_blit_0.obj
\GAMEDEVELOPMENT\output\SDL\SDL_blit_1.obj
\GAMEDEVELOPMENT\output\SDL\SDL_blit_A.obj
\GAMEDEVELOPMENT\output\SDL\SDL_blit_N.obj
\GAMEDEVELOPMENT\output\SDL\SDL_bmp.obj
\GAMEDEVELOPMENT\output\SDL\SDL_cdrom.obj
\GAMEDEVELOPMENT\output\SDL\SDL_cursor.obj
\GAMEDEVELOPMENT\output\SDL\SDL_dibaudio.obj
\GAMEDEVELOPMENT\output\SDL\SDL_dibevents.obj
\GAMEDEVELOPMENT\output\SDL\SDL_dibvideo.obj
\GAMEDEVELOPMENT\output\SDL\SDL_endian.obj
\GAMEDEVELOPMENT\output\SDL\SDL_error.obj
\GAMEDEVELOPMENT\output\SDL\SDL_events.obj
\GAMEDEVELOPMENT\output\SDL\SDL_expose.obj
\GAMEDEVELOPMENT\output\SDL\SDL_fatal.obj
\GAMEDEVELOPMENT\output\SDL\SDL_gamma.obj
\GAMEDEVELOPMENT\output\SDL\SDL_getenv.obj
\GAMEDEVELOPMENT\output\SDL\SDL_joystick.obj
\GAMEDEVELOPMENT\output\SDL\SDL_keyboard.obj
\GAMEDEVELOPMENT\output\SDL\SDL_mixer.obj
\GAMEDEVELOPMENT\output\SDL\SDL_mouse.obj
\GAMEDEVELOPMENT\output\SDL\SDL_pixels.obj
\GAMEDEVELOPMENT\output\SDL\SDL_quit.obj
\GAMEDEVELOPMENT\output\SDL\SDL_resize.obj
\GAMEDEVELOPMENT\output\SDL\SDL_RLEaccel.obj
\GAMEDEVELOPMENT\output\SDL\SDL_rwops.obj
\GAMEDEVELOPMENT\output\SDL\SDL_stretch.obj
\GAMEDEVELOPMENT\output\SDL\SDL_surface.obj
\GAMEDEVELOPMENT\output\SDL\SDL_syscdrom.obj
\GAMEDEVELOPMENT\output\SDL\SDL_sysevents.obj
\GAMEDEVELOPMENT\output\SDL\SDL_sysjoystick.obj
\GAMEDEVELOPMENT\output\SDL\SDL_sysmouse.obj
\GAMEDEVELOPMENT\output\SDL\SDL_sysmutex.obj
\GAMEDEVELOPMENT\output\SDL\SDL_syssem.obj
\GAMEDEVELOPMENT\output\SDL\SDL_systhread.obj
\GAMEDEVELOPMENT\output\SDL\SDL_systimer.obj
\GAMEDEVELOPMENT\output\SDL\SDL_syswm.obj
\GAMEDEVELOPMENT\output\SDL\SDL_thread.obj
\GAMEDEVELOPMENT\output\SDL\SDL_timer.obj
\GAMEDEVELOPMENT\output\SDL\SDL_video.obj
\GAMEDEVELOPMENT\output\SDL\SDL_wave.obj
\GAMEDEVELOPMENT\output\SDL\SDL_wingl.obj
\GAMEDEVELOPMENT\output\SDL\SDL_yuv.obj
\GAMEDEVELOPMENT\output\SDL\SDL_yuv_mmx.obj
\GAMEDEVELOPMENT\output\SDL\SDL_yuv_sw.obj
]
Creating command line "link.exe @c:\temp\RSP545.tmp"
<h3>Output Window</h3>
Linking...
   Creating library ../../../../output/SDL.lib and object ../../../../output/SDL.exp




<h3>Results</h3>
SDL.dll - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
