<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: ENGINE - Win32 (WCE ARM) Release--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "c:\temp\RSPD74.tmp" with contents
[
/nologo /W3 /Zi /O2 /Ob2 /I "../../OpenGL ES/include/" /I "../../PocketHAL/" /I "../../SDL/SDL//include" /I "../../SDL/SDL_image" /D "GAME_EDITOR_PROFESSIONAL" /D "STAND_ALONE_GAME" /D "KYRA_SUPPORT_OPENGL" /D _WIN32_WCE=300 /D "WIN32_PLATFORM_PSPC=310" /D "NDEBUG" /D "ARM" /D "_ARM_" /D UNDER_CE=300 /D "UNICODE" /D "_UNICODE" /D "_LIB" /FAs /Fa"../../output/PocketPC/engine/" /Fp"../../output/PocketPC/engine/ENGINE.pch" /YX /Fo"../../output/PocketPC/engine/" /Fd"../../output/PocketPC/engine/" /Oxs /MC /c 
"E:\GAMEDEVELOPMENT\kyra\engine\FastSprite.cpp"
]
Creating command line "clarm.exe @c:\temp\RSPD74.tmp" 
<h3>Output Window</h3>
Compiling...
FastSprite.cpp




<h3>Results</h3>
FastSprite.obj - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
